# -*- coding: utf-8 -*-
"""Movie_Recommmendation_System.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OdpxGtMT_hrhML6mMfGkoRGvJ7SLnYlD
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

movies = pd.read_csv("tmdb_5000_movies.csv")
credits = pd.read_csv("tmdb_5000_credits.csv")

movies.head()

credits.head()

movies.columns

credits.columns

print(len(movies))
print(len(credits))

print(movies.duplicated().sum())
print(credits.duplicated().sum())

print(movies.isnull().sum())

print(credits.isnull().sum())

movies=movies.merge(credits, on='title')

movies.shape

movies.columns

## let's remove the vague or unnecessary columns

movies=movies[['movie_id','title','overview','genres','keywords','cast','crew']]

movies.head()

movies.shape

print(movies.isnull().sum())

movies.iloc[0]

movies.iloc[0].genres

## It is string of list of dictionary
## SO we have to convert first in list

import ast

def convert(obj):
  genrelist=[]
  for i in ast.literal_eval(obj):
    genrelist.append(i['name'])
  return genrelist

movies['genres']=movies['genres'].apply(convert)

movies.iloc[0].keywords

movies['keywords']=movies['keywords'].apply(convert)

movies.iloc[0].cast

def convert1(obj):
  L=[]
  for i in ast.literal_eval(obj):
    L.append(i['name'])
  return L[:3]

movies['cast']=movies['cast'].apply(convert1)

movies.iloc[0].crew

def fetch_director(obj):
    try:
        data = ast.literal_eval(obj)
    except:
        return []
    return [i.get('name') for i in data if i.get('job') == 'Director']

movies['crew'] = movies['crew'].apply(fetch_director)

movies.head()

movies['overview'] = movies['overview'].fillna('').apply(lambda x: x.split())
movies.head()

movies['genres']=movies['genres'].apply(lambda x:[i.replace(" ","") for i in x])
movies['keywords']=movies['keywords'].apply(lambda x:[i.replace(" ","") for i in x])
movies['cast']=movies['cast'].apply(lambda x:[i.replace(" ","") for i in x])
movies['crew']=movies['crew'].apply(lambda x:[i.replace(" ","") for i in x])

movies.head()

movies['tags']=movies['overview']+movies['genres']+movies['keywords']+movies['cast']+movies['crew']
movies.head()

new_df=movies[['movie_id','title','tags']]
new_df.head()

new_df.loc[:, 'tags'] = new_df['tags'].apply(lambda x: " ".join(x))
new_df.head()

new_df.loc[:, 'tags']=new_df['tags'].apply(lambda x:x.lower())
new_df.head()

## Vectorization

from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=5000, stop_words='english')

vectors=cv.fit_transform(new_df['tags']).toarray()

vectors

print(cv.get_feature_names_out())

import nltk

from nltk import PorterStemmer
ps=PorterStemmer()

def stem(text):
  y=[]

  for i in text.split():
    y.append(ps.stem(i))

  return " ".join(y)

new_df.loc[:, 'tags'] = new_df['tags'].apply(stem)

vectors=cv.fit_transform(new_df['tags']).toarray()
vectors

cv.get_feature_names_out()

from sklearn.metrics.pairwise import cosine_similarity

similarity=cosine_similarity(vectors)

cosine_similarity(vectors).shape

similarity[0] ## Tells the similarity of the movies of index 1 with all other movies

def recommend(movies):
  movie_index=new_df[new_df['title']==movies].index[0]
  distances=similarity[movie_index]
  movies_list=sorted(list(enumerate(distances)), reverse=True, key=lambda x:x[1])[1:6]

  for  i in movies_list:
    print(new_df.iloc[i[0]].title)

recommend('Batman Begins')

import pickle

pickle.dump(new_df.to_dict(), open('movies_dict.pkl', 'wb'))

pickle.dump(similarity, open('similarity.pkl', 'wb'))

pickle.dump(similarity, open('poster_dict.pkl', 'wb'))

import os
import requests
import time

API_KEY = "8265bd1679663a7ea12ac168da84d2e8"

movies = pd.DataFrame(pickle.load(open("movies_dict.pkl", "rb")))

if os.path.exists("poster_dict1.pkl"):
    poster_list = pickle.load(open("poster_dict1.pkl", "rb"))
    start_index = len(poster_list)
    print(f"Resuming from index {start_index}")
else:
    poster_list = []
    start_index = 0
    print("Starting fresh")

for idx in range(start_index, len(movies)):
    movie_id = movies.iloc[idx].movie_id
    try:
        url = f"https://api.themoviedb.org/3/movie/{movie_id}?api_key={API_KEY}"
        data = requests.get(url, timeout=10).json()
        poster_path = data.get("poster_path")

        if poster_path:
            poster_list.append("https://image.tmdb.org/t/p/w500" + poster_path)
        else:
            poster_list.append(None)
    except:
        poster_list.append(None)

    # save progress every 50 movies (important)
    if idx % 100 == 0:
        pickle.dump(poster_list, open("poster_dict1.pkl", "wb"))
        print(f"Saved up to {idx}")

    time.sleep(0.25)

pickle.dump(poster_list, open("poster_dict1.pkl", "wb"))
print("Poster pickle recreated successfully")

